### ISSUE TITLE
Throwing an error when trying to use keyword DISTINCT

### ISSUE THREAD

**Issue by arjandedgjonaj** [oguimbal/pg-mem#19] opened 2020-12-27 06:42 UTC
Replicate: 
Try to run a query "SELECT DISTINCT fieldName FROM tableName." 

Error:
Didn't recognized keyword DISTINCT

**Comment by oguimbal** [comment] 2020-12-27 08:49
Duplicate of #14

**Closed by oguimbal** 2020-12-27 08:49 UTC
