### ISSUE TITLE
Getting an odd error in relation to `col_description`

### ISSUE THREAD

**Issue by MirrorBytes** [oguimbal/pg-mem#46] opened 2021-01-28 16:17 UTC
I'm rewriting my project completely, and trying to implement `pg-mem`. However, I'm getting this error when trying to initialize and sync the database:

```error
QueryFailedError: column "columns.table_name" does not exist

    🐜 This seems to be an execution error, which means that your request syntax seems okay,
    but the resulting statement cannot be executed → Probably not a pg-mem error.

    *️⃣ Failed SQL statement:
                SELECT columns.*,
                  pg_catalog.col_description(('"' || table_catalog || '"."' || table_schema || '"."' || table_name || '"')::regclass::oid, ordinal_position) AS description,
                  ('"' || "udt_schema" || '"."' || "udt_name" || '"')::"regtype" AS "regtype",
                  pg_catalog.format_type("col_attr"."atttypid", "col_attr"."atttypmod") AS "format_type"
                  FROM "information_schema"."columns"
                  LEFT JOIN "pg_catalog"."pg_attribute" AS "col_attr"
                  ON "col_attr"."attname" = "columns"."column_name"
                  AND "col_attr"."attrelid" = (
                    SELECT
                      "cls"."oid" FROM "pg_catalog"."pg_class" AS "cls"
                      LEFT JOIN "pg_catalog"."pg_namespace" AS "ns"
                      ON "ns"."oid" = "cls"."relnamespace"
                    WHERE "cls"."relname" = "columns"."table_name"
                    AND "ns"."nspname" = "columns"."table_schema"
                  )
                WHERE
                ("table_schema" = 'public' AND "table_name" = 'submission') OR ("table_schema" = 'public' AND "table_name" = 'form') OR ("table_schema" = 'public' AND "table_name" = 'user');

    👉 You can file an issue at https://github.com/oguimbal/pg-mem along with a way to reproduce this error (if you can), and  the stacktrace:

      at new QueryFailedError (../../src/error/QueryFailedError.ts:9:9)
      at PostgresQueryRunner.<anonymous> (../../src/driver/postgres/PostgresQueryRunner.ts:228:19)
      at step (../../node_modules/typeorm/node_modules/tslib/tslib.js:141:27)
      at Object.throw (../../node_modules/typeorm/node_modules/tslib/tslib.js:122:57)
      at rejected (../../node_modules/typeorm/node_modules/tslib/tslib.js:113:69)
```

**Comment by oguimbal** [comment] 2021-01-28 16:38
Duplicate of #38

The issue being that a subrequest (the inner "select" in your condition) is using a reference to a parent request (here "columns")).

I'm working on it. Tough nut to crack (I must refactor some things a bit to fix that)

**Closed by oguimbal** 2021-01-28 16:38 UTC

**Comment by MirrorBytes** [comment] 2021-01-28 16:46
I assumed it had something to do with that considering the complexity of nested queries. It's odd that my previous iteration of the project works still though. I'll wait for your updates patiently!
