### ISSUE TITLE
Insert Statement Fails with no Useful Error

### ISSUE THREAD

**Issue by dschinkel** [oguimbal/pg-mem#31] opened 2021-01-12 02:22 UTC
I'm having a hard time troubleshooting this.  

While I can log any failed sql statements that pg-mem via `inMemoryDb.on('query-failed'`, it doesn't tell me what the problem is exactly.

This query was successfully migrated to my production database using flyway.   This same kind of statement also ran ok in my `001` migration but just not my `003` for this community table insert which is really odd.

Here's a screencast on this: https://youtu.be/yaWBzsUtJbE

(note: _I've replaced the real strings with x's for privacy for this post_)
```js
INSERT INTO public.community (name,image_url,twitter_url,coordinates,meetup_url,main_site_url,slack_url,facebook_url,github_url,eventbrite_url,linkedin_url) VALUES ('xxxxxxxxxx','xxxxxxxxxxx',NULL,'(33.7676338,-84.6176515)','xxxxxxxxxx',NULL,NULL,NULL,NULL,NULL,NULL);
```
Also tried

```js
INSERT INTO community VALUES ('Software Crafters - Atlanta','https://storage.googleapis.com/wedotdd-client-assets/assets/communities/assets_communities_software-crafters-atlanta.png',NULL,point(33.7676338,-84.6176515),'https://www.meetup.com/Software-Craftsmanship-Atlanta',NULL,NULL,NULL,NULL,NULL,NULL);
```

Now the initial migration that creates the schema looks like this for my pg-mem 001 migration for the community table:

```
CREATE TABLE community (
    community_id integer NOT NULL,
    name character varying NOT NULL,
    image_url character varying,
    twitter_url character varying,
    coordinates point,
    meetup_url character varying,
    main_site_url character varying,
    slack_url character varying,
    facebook_url character varying,
    github_url character varying,
    eventbrite_url character varying,
    linkedin_url character varying
);

ALTER TABLE community ALTER COLUMN community_id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME community_community_id_seq
    START WITH 0
    INCREMENT BY 1
    MINVALUE 0
    NO MAXVALUE
    CACHE 1
);
```

The only thing to note in addition is that in my 001 migration related to community at the end of that script is:
```js
ALTER TABLE ONLY community_location ADD CONSTRAINT community_country_pkey PRIMARY KEY (community_id, location_id);
ALTER TABLE ONLY community ADD CONSTRAINT community_pkey PRIMARY KEY (community_id);
ALTER TABLE ONLY location ADD CONSTRAINT location_pkey PRIMARY KEY (location_id);
ALTER TABLE ONLY skill_type ADD CONSTRAINT skill_type_pkey PRIMARY KEY (skill_type_id);
ALTER TABLE ONLY skills ADD CONSTRAINT skills_pkey PRIMARY KEY (skill_id);
ALTER TABLE ONLY location ADD CONSTRAINT city_id_fk FOREIGN KEY (city_id) REFERENCES city(city_id) MATCH FULL;
ALTER TABLE ONLY community_location ADD CONSTRAINT community_id_fk FOREIGN KEY (community_id) REFERENCES community(community_id) MATCH FULL;
ALTER TABLE ONLY location ADD CONSTRAINT country_id_fk FOREIGN KEY (country_id) REFERENCES country(country_id) MATCH FULL;
ALTER TABLE ONLY community_location ADD CONSTRAINT location_id_fk FOREIGN KEY (location_id) REFERENCES location(location_id) MATCH FULL;
ALTER TABLE ONLY location ADD CONSTRAINT state_id_fk FOREIGN KEY (state_id) REFERENCES state(state_id) MATCH FULL;
```

If I disable those ALTER statements at then end then change the script to include the community_id, then this works (noice the ID 31):
```js
INSERT INTO community VALUES (31, 'xxxxx', 'xxxxx', NULL, '(-77.03059944399082,-12.045945732454783)', 'xxxxx', NULL, NULL, NULL, NULL, NULL, NULL);
```

But..I should not have to disable those alter statements AND I shouldn't have to specify a community_id in my insert because I've turned on `ADD GENERATED ALWAYS AS IDENTITY` which will create the ID for me automatically.

**Comment by oguimbal** [comment] 2021-01-12 08:22
Hi !

First, the actual error comes, in my opinion, from the `point(x, y)` bit.  This is a function, which is not defined in pg-mem. You could either define it yourself, or use the literal syntax to build points, which is via the string `'(x,y)`  or just `'x,y'`.

Now, why you dont see any error.

As you probably have noticed, `sql statement failed` string comes from your subscription to `query-failed`, which should indeed include the exception as an argument, but that's not the problem.

As I mentioned previously, your module is creating a [dettached promise](https://stackoverflow.com/questions/40228209/why-are-javascript-promises-resolving-out-of-order). You should avoid doing that. Instead, this is what you should do:

```typescript
import {newDb, IMemoryDb, IBackup} from 'pg-mem';

let db: IMemoryDb;
let backup: IBackup;

export async function getDb(): Promise<IMemoryDb> {
    if (backup) {
         // if db already created, then restore data as it was after migration
         backup.restore();
         return db;
    }

   // else, create db & migrate
    db = newDb();
    await db.migrate();
    backup = db.backup(); 
    return db;
}
```

And in your tests, you thus will be forced to use the async version:

```
import {getDb} from './test-db';
...
it ('tests something', async () => {
    const db = await getDb(); // await it !
});
```

That way, the exception will be rethrown in your test, and you should see something like "function 'point' is not supported" or whatever error details you're looking for.

![image](https://user-images.githubusercontent.com/8973947/104288081-9d50d200-54b7-11eb-84ee-e73b532f528c.png)

Again, you should be very much be aware of how async/await work, and of what a dettached promise is, this is a very common source of unpredictable, unrepeatable and incomprehensible errors.

**Closed by oguimbal** 2021-01-12 08:22 UTC

**Comment by dschinkel** [comment] 2021-01-12 08:23
Sigh, I think I might have found it
>If you attempt to insert (or update) values into the GENERATED ALWAYS AS IDENTITY column, PostgreSQL will issue an error.

https://www.postgresqltutorial.com/postgresql-identity-column/

**Comment by oguimbal** [comment] 2021-01-12 09:01
There still is a dettached promise line 2 here.

This cannot work well. It might work by accident, but there are concurrency issues with this, meaning that it might have an erratic behaviour, and might behave otherwise on another machine than yours.

The point literal syntax works well, as far as I can tell:

![image](https://user-images.githubusercontent.com/8973947/104292273-ec4d3600-54bc-11eb-8506-6195c06f393a.png)

Can you post an example that you can reproduce [in the playground](https://oguimbal.github.io/pg-mem-playground/) if its not the case for you ?

**Comment by dschinkel** [comment] 2021-01-12 09:03
yea I thought that since I was using an IIFE, this code was synchronous meaning backup() wouldn't happen until after `(async () => await migrate())();` is done.  I must be wrong.

**Comment by dschinkel** [comment] 2021-01-12 09:10
for Christ sakes
![Screen Shot 2021-01-12 at 3 10 23 AM](https://user-images.githubusercontent.com/338798/104293588-c5bed900-5483-11eb-8432-ad34287c63c6.jpg)

**Comment by oguimbal** [comment] 2021-01-12 09:51
Yea, you cant await on a top level (actually, it has been allowed by ecmascript about a year ago if i remember right, but you just shoulnt yet).

That's why you have to wrap that in an exported async function
```typescript

export async function setupOrWhatever() {
   // do your things
}
```
... or stop using .migrate(), which is async, to run a migration yourself, in a synchronous fashion.

That said, all this seem very unrelated to pg-mem to me. That's more about genral JS stuff.

**Comment by dschinkel** [comment] 2021-01-12 09:52
Yea I know how async works.  What's a pain is commonJS and typescript care causing me a lot of pain with all this.

**Comment by oguimbal** [comment] 2021-01-12 10:06
Nope, migrate is actually on `ISchema`, that was just a mistake because I wrote this code directly in github, so that's actually `db.public.migrate()`  (or `db.getSchema('myOtherSchema').migrate()` if you'd like to migrate another schema)

By "stop using migrate()" I meant that if you dont want to carry promises around, you could just avoid calling `migrate()` and do something like   `db.public.none(fs.readFileSync(path.join(__dirname, 'myfile.sql'), 'utf8')`, which is synchronous.

**Comment by dschinkel** [comment] 2021-01-12 10:08
eya well `db.public.none(fs.readFileSync(path.join(__dirname, 'myfile.sql'), 'utf8')` defeats the point of using migrate which gives me essentials I need to use pg-mem.

**Comment by dschinkel** [comment] 2021-01-12 10:21
I'm going to post a new issue on all this, there are still issues with trying to use the example you showed.  I've tried things on my side but there's some issues that I think on the pg-mem side need to be looked at still.

**Comment by oguimbal** [comment] 2021-01-12 10:25
Like I said in my previous comment, the migrate() function is **NOT** directly on the `IMemoryDb`, it is on the `ISchema` interface.

```typescript
await db.public.migrate(); // this

await db.getSchema('mySchema').migrate(); // or this, if you have multiple schemas
```
