### ISSUE TITLE
Cannot run Insert Statement based on Select

### ISSUE THREAD

**Issue by dschinkel** [oguimbal/pg-mem#45] opened 2021-01-22 03:32 UTC
So I can't do [Unexpected kw_do token: "do"](https://github.com/oguimbal/pg-mem/issues/37)
And I can't do [Support for aggregate function max](https://github.com/oguimbal/pg-mem/issues/36)

And now looking for a way to dumb this down so that pg-mem can actually run some migrations I must be able to run, but I can't run any of these dumbed down statements either:
```sql
INSERT INTO city (name,state_id)
select 'Atlanta', community_id from community where community.name = 'Test Name';
```
or
```sql
INSERT INTO city (name, state_id) (select 'Atlanta', community_id from community where community.name = 'Test Name'');
```
or
```sql
INSERT INTO city (name, state_id) ((select 'Atlanta', community_id from community where community.name = 'Test Name'));
```
or
```sql
INSERT INTO city (name, state_id)
VALUES ((select 'Alanta' as name), (select community_id from community where community.name = 'Test Name'));
```
or
```sql
INSERT INTO city (name, state_id) VALUES
(('Atlanta'), (select community_id from community where community.name = 'Test Name'));
```

**Example error** (got this on the first example above) :
```
Error: todo: array-mode iteration
💥 This is a nasty error, which was unexpected by pg-mem. Also known "a bug" 😁 Please file an issue !

*️⃣ Failed SQL statement: INSERT INTO city (name, state_id)
select 'Atlanta', community_id from community where community.name = 'Test Name';
```

So what do I do now? How can I get this insert working?  This isn't an advanced _thang_.

I've got to be able to run these at the very least if you don't support `PL/pgSQL` yet, this is the only alternative I can think of to get my stuff hopefully to continue to work in pg-mem in the dumbest way possible.

**Comment by oguimbal** [comment] 2021-01-22 08:44
Duplicate of #35

**Closed by oguimbal** 2021-01-22 08:44 UTC

**Comment by dschinkel** [comment] 2021-01-23 02:20
Well I can't move forward using this until this works.  This is like the last hurdle for me to be able to fully use pg-mem now.  I must be able to do these kind of inserts.
