### ISSUE TITLE
QueryFailedError: column "columns.table_name" does not exist 

### ISSUE THREAD

**Issue by dneelapareddy** [oguimbal/pg-mem#61] opened 2021-02-11 15:13 UTC
Issue: 

`Failed SQL statement: 
                SELECT columns.*,
                  pg_catalog.col_description(('"' || table_catalog || '"."' || table_schema || '"."' || table_name || '"')::regclass::oid, ordinal_position) AS description,
                  ('"' || "udt_schema" || '"."' || "udt_name" || '"')::"regtype" AS "regtype",
                  pg_catalog.format_type("col_attr"."atttypid", "col_attr"."atttypmod") AS "format_type"
                  FROM "information_schema"."columns"
                  LEFT JOIN "pg_catalog"."pg_attribute" AS "col_attr"
                  ON "col_attr"."attname" = "columns"."column_name"
                  AND "col_attr"."attrelid" = (
                    SELECT
                      "cls"."oid" FROM "pg_catalog"."pg_class" AS "cls"
                      LEFT JOIN "pg_catalog"."pg_namespace" AS "ns"
                      ON "ns"."oid" = "cls"."relnamespace"
                    WHERE "cls"."relname" = "columns"."table_name"
                    AND "ns"."nspname" = "columns"."table_schema"
                  )
                WHERE
                ("table_schema" = 'public' AND "table_name" = 'user')`

When: While trying to run the example from https://github.com/oguimbal/pg-mem/blob/master/samples/typeorm/simple.ts in my project

**Comment by oguimbal** [comment] 2021-02-11 15:23
Hi, thanks for the report.

What is the actual error ?

My bet: You're using Typeorm version > 0.2.29 ... in which case this is a duplicate of #53, and it will be fixed by #38

In which case, you can either wait for #38 to be fixed, or downgrade to Typeorm 0.2.29

I'm closing this, reopen if i'm wrong 😊

**Closed by oguimbal** 2021-02-11 15:23 UTC
