### ISSUE TITLE
Getting an error Unexpected kw_limit token: "limit".

### ISSUE THREAD

**Issue by NileshKale-Globant** [oguimbal/pg-mem#174] opened 2021-11-24 16:56 UTC
# Description
I am trying to execute the query with offset and limit, but the scripts throws an error **Unexpected kw_limit token: "limit".**
(Could be related with the [issue](https://github.com/oguimbal/pg-mem/issues/97))

# Project Description

![image](https://user-images.githubusercontent.com/89136696/143281301-607c8c6d-1ad2-4a6f-a802-da6138bc5577.png)

My project includes the "**src**" directory which have two file.
**1. Demo.ts** is the entity file with id and name as column of the demo table

```
import {
  Column,
  Entity,
  PrimaryGeneratedColumn,
} from 'typeorm';

@Entity()
export class Demo {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column({ nullable: false, length: 200 })
  name: string;

}

```
**2. index.ts** file have the logic to execute the query with pg-mem configuration

```
import { newDb } from 'pg-mem';
import { Demo } from './Demo';

async function start() {

    let db = newDb();
    await db.adapters.createTypeormConnection({
        type: 'postgres',
        entities: [
            Demo
        ],
        logging: true
    });

    try {

        let result = db.public.query(`SELECT * from demo OFFSET 0 LIMIT 10`);
        console.log(`Query executed successfully.`);
        console.log(result);

    } catch (error) {
        console.log('Error occurred while executing the query');
        console.log(error);
    }
}

start();

```
My **package.json** file have following content

````
{
  "name": "pg-mem-issue",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "execute": "tsc && node ./build/index.js"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "pg-mem": "1.9.14",
    "typeorm": "^0.2.29"
  }
}
````

and **tsconfig.json** file have following content

````
{
  "compilerOptions": {
    "lib": ["es2020", "DOM"],
    "module": "commonjs",
    "declaration": true,
    "removeComments": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es2020",
    "sourceMap": true,
    "rootDir": "./src",
    "outDir": "./build",
    "esModuleInterop": true,
    "noUnusedLocals": true,
    "skipLibCheck": true
  },
  "exclude": ["node_modules", "build"]
}

````

But when I tries to execute the script **npm run execute** (available in package.json file), it give me the following error.
Note:
Install the dependency before execute the script

````
QueryError: 💔 Your query failed to parse.
This is most likely due to a SQL syntax error. However, you might also have hit a bug, or an unimplemented feature of pg-mem.
If this is the case, please file an issue at https://github.com/oguimbal/pg-mem along with a query that reproduces this syntax error. 

👉 Failed query:

    SELECT * from demo OFFSET 0 LIMIT 10;

💀 Syntax error at line 1 col 29:

  SELECT * from demo OFFSET 0 LIMIT
                              ^
Unexpected kw_limit token: "limit". Instead, I was expecting to see one of the following:

    - A "op_cast" token
    - A "lbracket" token
    - A "op_member" token
    - A "op_membertext" token
    - A "word" token
    - A "op_exp" token
    - A "star" token
    - A "op_div" token
    - A "op_mod" token
    - A "op_plus" token
    - A "op_minus" token
    - A "op_additive" token
    - A "kw_not" token
    - A "kw_in" token
    - A "kw_not" token
    - A "op_like" token
    - A "op_ilike" token
    - A "op_not_like" token
    - A "op_not_ilike" token
    - A "kw_like" token
    - A "kw_ilike" token
    - A "ops_others" token
    - A "kw_not" token
    - A "kw_is" token
    - A "kw_notnull" token
    - A "kw_is" token
    - A "kw_isnull" token
    - A "kw_is" token
    - A "word" token
    - A "op_compare" token
    - A "op_eq" token
    - A "op_neq" token
    - A "kw_and" token
    - A "word" token
    - A "word" token
    - A "kw_or" token
    - A "kw_fetch" token
    - A "kw_union" token
    - A "semicolon" token


    at Object.parseSql (E:\GreatMinds\Tasks\Sprint 22\pg-mem-issue-req\node_modules\pg-mem\index.js:3961:15)
    at DbSchema.parse (E:\GreatMinds\Tasks\Sprint 22\pg-mem-issue-req\node_modules\pg-mem\index.js:4461:30)
    at DbSchema.queries (E:\GreatMinds\Tasks\Sprint 22\pg-mem-issue-req\node_modules\pg-mem\index.js:4468:31)
    at queries.next (<anonymous>)
    at DbSchema.query (E:\GreatMinds\Tasks\Sprint 22\pg-mem-issue-req\node_modules\pg-mem\index.js:4449:20)
    at start (E:\GreatMinds\Tasks\Sprint 22\pg-mem-issue-req\build\index.js:15:32) {
  data: {
    error: '💔 Your query failed to parse.\n' +
      'This is most likely due to a SQL syntax error. However, you might also have hit a bug, or an unimplemented feature of pg-mem.\n' +
      'If this is the case, please file an issue at https://github.com/oguimbal/pg-mem along with a query that reproduces this syntax 
error.\n' +
      '\n' +
      '👉 Failed query:\n' +
      '\n' +
      '    SELECT * from demo OFFSET 0 LIMIT 10;\n' +
      '\n' +
      '💀 Syntax error at line 1 col 29:\n' +
      '\n' +
      '  SELECT * from demo OFFSET 0 LIMIT\n' +
      '                              ^\n' +
      'Unexpected kw_limit token: "limit". Instead, I was expecting to see one of the following:\n' +
      '\n' +
      '    - A "op_cast" token\n' +
      '    - A "lbracket" token\n' +
      '    - A "op_member" token\n' +
      '    - A "op_membertext" token\n' +
      '    - A "word" token\n' +
      '    - A "op_exp" token\n' +
      '    - A "star" token\n' +
      '    - A "op_div" token\n' +
      '    - A "op_mod" token\n' +
      '    - A "op_plus" token\n' +
      '    - A "op_minus" token\n' +
      '    - A "op_additive" token\n' +
      '    - A "kw_not" token\n' +
      '    - A "kw_in" token\n' +
      '    - A "kw_not" token\n' +
      '    - A "op_like" token\n' +
      '    - A "op_ilike" token\n' +
      '    - A "op_not_like" token\n' +
      '    - A "op_not_ilike" token\n' +
      '    - A "kw_like" token\n' +
      '    - A "kw_ilike" token\n' +
      '    - A "ops_others" token\n' +
      '    - A "kw_not" token\n' +
      '    - A "kw_is" token\n' +
      '    - A "kw_notnull" token\n' +
      '    - A "kw_is" token\n' +
      '    - A "kw_isnull" token\n' +
      '    - A "kw_is" token\n' +
      '    - A "word" token\n' +
      '    - A "op_compare" token\n' +
      '    - A "op_eq" token\n' +
      '    - A "op_neq" token\n' +
      '    - A "kw_and" token\n' +
      '    - A "word" token\n' +
      '    - A "word" token\n' +
      '    - A "kw_or" token\n' +
      '    - A "kw_fetch" token\n' +
      '    - A "kw_union" token\n' +
      '    - A "semicolon" token\n' +
      '\n',
    code: undefined
  }
}
````
# pg-mem version

pg-mem : 1.9.3
typeorm : 0.2.29

The issue is raised for the following versions combination also
pg-mem: 2.1.9
typeorm: 0.2.29

**Comment by NileshKale-Globant** [comment] 2021-11-24 17:05
@oguimbal 
Could you have a look on this issue?

**Comment by oguimbal** [comment] 2021-11-24 17:10
Hi @NileshKale-Globant ,

This issue is a parser bug, and is a duplicate of [this one](https://github.com/oguimbal/pgsql-ast-parser/issues/65).
Subscribe to the other issue to be notified when I fix it !

Workaround:  Invert the `LIMIT` and the `OFFSET` clauses (Use `LIMIT x OFFSET y` instead of `OFFSET y LIMIT x`)

**Closed by oguimbal** 2021-11-24 17:10 UTC
