### ISSUE TITLE
Simple query with Multiple Aliases Not Parsing

### ISSUE THREAD

**Issue by dschinkel** [oguimbal/pg-mem#57] opened 2021-02-10 05:44 UTC
For some reason, it can't parse this but this is a valid query:

```sql
SELECT c.community_id,
       l.location_id
FROM community c,
     location l
WHERE c.name = 'test'
AND l.name = 'test2';
```

**Error**
```sql
 '\n' +
      '💀 Syntax error at line 11 col 17:\n' +
      '\n' +
      '  FROM community c,\n' +
      '                  ^\n' +
      'Unexpected comma token: ",". Instead, I was expecting to see one of the following:\n' +
      '\n' +
      '    - A "kw_left" token\n' +
      '    - A "kw_right" token\n' +
      '    - A "kw_full" token\n' +
      '    - A "kw_inner" token\n' +
      '    - A "kw_where" token\n' +
      '    - A "kw_group" token\n' +
```

**Comment by oguimbal** [comment] 2021-02-10 08:13
Hi, that's a [cartesian product, or cross join](https://en.wikipedia.org/wiki/Join_(SQL)#Cross_join), which is not yet supported. This is a duplicate of #26 :)

**Closed by oguimbal** 2021-02-10 08:13 UTC
