### ISSUE TITLE
Type "regclass"

### ISSUE THREAD

**Issue by MirrorBytes** [oguimbal/pg-mem#4] opened 2020-11-25 17:28 UTC
This type is specific to table relations and casting to OIDs for internal relations. I believe this type is used by TypeORM for the relationship decorators.

Is there a possibility of this being implemented in the future?

<details>
<summary>Error for reference:</summary>

```error
Error: Not supported: Type "regclass"
          at Object.fromNative (/home/bobby/phorm-new/node_modules/pg-mem/src/datatypes.ts:858:19)
          at _buildValueReal (/home/bobby/phorm-new/node_modules/pg-mem/src/predicate.ts:82:26)
          at _buildValue (/home/bobby/phorm-new/node_modules/pg-mem/src/predicate.ts:33:11)
          at _buildValueReal (/home/bobby/phorm-new/node_modules/pg-mem/src/predicate.ts:81:20)
          at _buildValue (/home/bobby/phorm-new/node_modules/pg-mem/src/predicate.ts:33:11)
          at /home/bobby/phorm-new/node_modules/pg-mem/src/predicate.ts:77:44
          at Array.map (<anonymous>)
          at _buildValueReal (/home/bobby/phorm-new/node_modules/pg-mem/src/predicate.ts:77:35)
          at _buildValue (/home/bobby/phorm-new/node_modules/pg-mem/src/predicate.ts:33:11)
          at Object.buildValue (/home/bobby/phorm-new/node_modules/pg-mem/src/predicate.ts:16:12)
          at new Selection (/home/bobby/phorm-new/node_modules/pg-mem/src/transforms/selection.ts:132:28)
          at Object.buildSelection (/home/bobby/phorm-new/node_modules/pg-mem/src/transforms/selection.ts:30:12)
          at OrFilter.select (/home/bobby/phorm-new/node_modules/pg-mem/src/transforms/transform-base.ts:46:20)
          at Query.buildSelect (/home/bobby/phorm-new/node_modules/pg-mem/src/query.ts:399:23)
          at Query.queries (/home/bobby/phorm-new/node_modules/pg-mem/src/query.ts:98:47)
          at queries.next (<anonymous>)
          at Query.query (/home/bobby/phorm-new/node_modules/pg-mem/src/query.ts:42:20)
          at /home/bobby/phorm-new/node_modules/pg-mem/src/adapters.ts:81:80
          at Timeout.task [as _onTimeout] (/home/bobby/phorm-new/node_modules/jsdom/lib/jsdom/browser/Window.js:391:19)
          at listOnTimeout (internal/timers.js:554:17)
          at processTimers (internal/timers.js:497:7)
```
</details>

**Comment by oguimbal** [comment] 2020-11-25 17:57
Yup, that's very much in the the scope. 

It's not a trivial feature though (but will be necesary to improve how pg-mem deals with reflection), so I cant say exactly when it will be released.

(if someone else also needs this, please comment in order to help priorizing it)

**Comment by MirrorBytes** [comment] 2020-11-25 18:15
Understood completely. Regclass is a pain to deal with in regular postgres.

**Comment by xpportal-bmo** [comment] 2020-12-04 16:24
+1 This would be very useful for the project I'm working on.

BTW, great work on all of this. Being able to use postgres instead of sqlite in my unit tests will be amazing.

**Comment by oguimbal** [comment] 2020-12-04 16:55
Duly noted.
I'll implement that asap.

Thanks :) That's nice to hear.

**Comment by BrownKnight** [comment] 2020-12-07 22:42
Another +1 from me, very much looking forward to seeing where this goes - looks to be an incredibly useful tool.

**Comment by oguimbal** [comment] 2020-12-08 09:30
Could you provide examples of how you use regclasses ?

(i'm looking for inspiration to write some tests, and I'd like to cover some actual use cases)

**Comment by BrownKnight** [comment] 2020-12-08 12:44
I'll be honest I'm not hugely experienced with how TypeORM uses regclasses, aside from the fact that it not being supported meant that my TypeORM relations didn't work. The sample you already have at [/samples/typeorm/joins.ts](https://github.com/oguimbal/pg-mem/blob/master/samples/typeorm/joins.ts) is pretty much a solid use case. I'm not sure if using the DataMapper approach vs ActiveRecord affects how TypeORM deals with relations, but would be worth testing with both I think.

I have just tried to create a minimal repo with some use cases where I've encountered the need to have regclasses previously, however trying to run that sample file resulted in an error when synchronising (I've most likely done something wrong admittedly):
```
Error: No alias provided
        at Query.buildSelect (/Users/aman/pg-mem-regclass-usage/node_modules/pg-mem/src/query.ts:354:23)
        at Query.queries (/Users/aman/pg-mem-regclass-usage/node_modules/pg-mem/src/query.ts:98:47)
        at queries.next (<anonymous>)
        at Query.query (/Users/aman/pg-mem-regclass-usage/node_modules/pg-mem/src/query.ts:42:20)
```

When I've got some more time later this week I'll delve a little deeper and come up with a few use cases.

**Comment by MirrorBytes** [comment] 2020-12-08 13:45
Agree with @BrownKnight, the only additional tests around it you would need for basic functionality is using something like:

```typescript
const photo = await Photo.find({ id }, { relations: [ 'user' ] });
```

This will trigger a regclass due to named relations. Now this will try to convert the named relations to OID relations.
After that, I would run some basic functions, like test adds and deletes.

**Comment by oguimbal** [comment] 2020-12-09 09:52
Hi ! 

I'm not sure to see which request is failing (the `join.ts` sample works for me... it actually is a unit test that prevents from deploying if failing).

However, I implemented regclass (at least part of it) in `pg-mem@1.4.0` ,  could you try it ?

**Comment by MirrorBytes** [comment] 2020-12-09 14:52
Tested it out, now I get this error:

```error
QueryFailedError: 🔨 Not supported 🔨 : Type "oid"
```

This tells me that you're getting closer.
Here's some good info that may help implementing oids:

"The oid type itself has few operations beyond comparison. It can be cast to integer, however, and then manipulated using the standard integer operators. (Beware of possible signed-versus-unsigned confusion if you do this.)

The OID alias types have no operations of their own except for specialized input and output routines. These routines are able to accept and display symbolic names for system objects, rather than the raw numeric value that type oid would use. The alias types allow simplified lookup of OID values for objects. For example, to examine the pg_attribute rows related to a table mytable, one could write:"

```sql
SELECT * FROM pg_attribute WHERE attrelid = 'mytable'::regclass;
```

"rather than:"

```sql
SELECT * FROM pg_attribute
  WHERE attrelid = (SELECT oid FROM pg_class WHERE relname = 'mytable');
```

**Comment by MirrorBytes** [comment] 2020-12-09 15:02
There's absolutely nothing special with my database, I'm just using sync for the time being. Here are the simplified entities I'm using with relations:

### `base.ts`
```typescript
import {
  BaseEntity,
  PrimaryGeneratedColumn,
  CreateDateColumn,
  BeforeInsert,
  BeforeUpdate,
} from 'typeorm';
import { validateOrReject } from 'class-validator';
import { ObjectType, Field, ID } from 'type-graphql';

@ObjectType()
export abstract class External extends BaseEntity {
  @Field(() => ID)
  @PrimaryGeneratedColumn('uuid')
  readonly id!: string;

  @Field()
  @CreateDateColumn({ type: 'timestamp' })
  createdAt!: Date;

  @Field()
  @CreateDateColumn({ type: 'timestamp' })
  updatedAt!: Date;

  @BeforeInsert()
  @BeforeUpdate()
  async validate(): Promise<void> {
    await validateOrReject(this);
  }
}
```

### `user.ts`
```typescript
import { Entity, Column, OneToMany } from 'typeorm';
import { ObjectType, Field } from 'type-graphql';
import { IsEmail, Length } from 'class-validator';

import { External } from './base';
import { Form } from './form';

@Entity()
@ObjectType()
export class User extends External {
  @Field()
  @Column('citext', { unique: true })
  @IsEmail()
  email!: string;

  @Field()
  @Column()
  @Length(1, 64)
  name!: string;

  @Column({ type: 'bytea' })
  password!: Buffer;

  @OneToMany(() => Form, (form) => form.user)
  forms!: Form[];

  ...
}
```

### `form.ts`
```typescript
import { Entity, Column, ManyToOne, OneToMany } from 'typeorm';
import { ObjectType, Field } from 'type-graphql';
import { MaxLength } from 'class-validator';

@Entity()
@ObjectType()
export class Form extends External {
  @Field()
  @MaxLength(60)
  @Column()
  name!: string;

  @Field(() => User, { nullable: true })
  @ManyToOne(() => User, (user) => user.forms)
  user!: User;

  ...

  @OneToMany(() => Submission, (submission) => submission.form, {
    cascade: true,
  })
  submissions!: Submission[];

  ...
}
```

### `submission.ts`
```typescript
import { Entity, Column, ManyToOne } from 'typeorm';
import { ObjectType } from 'type-graphql';

@Entity()
@ObjectType()
export class Submission extends External {
  ...

  @ManyToOne(() => Form, (form) => form.submissions, { onDelete: 'CASCADE' })
  form!: Form;
}
```

**Comment by BrownKnight** [comment] 2020-12-09 17:33
It appears the issues @MirrorBytes is seeing may be due something TypeORM has changed between v0.2.25 and the latest version. I've run the joins.ts file on every version since v0.2.25, and it only gives the old type not found error in v0.2.29 (latest)

**Comment by oguimbal** [comment] 2020-12-09 17:49
Good catch ! I'm using 0.2.25 ... that's why 👍  thanks, i'll have a look.

**Comment by MirrorBytes** [comment] 2020-12-09 17:59
I'm using 0.2.29 as well, but I'm getting the oid not supported error

**Comment by oguimbal** [comment] 2020-12-09 19:14
@MirrorBytes   FYI I've created [a unit test](https://github.com/oguimbal/pg-mem/blob/master/src/tests/irl-tests/mirrorbytes.spec.ts)  that matches your use case.

And we're almost there... oid is now supported (1.4.1), but `on delete cascade` is not.
I'll implement that :)

> 🔨 Not supported 🔨 : Foreign keys with actions not yet supported

**Comment by MirrorBytes** [comment] 2020-12-09 19:49
@oguimbal Awesome! Really looking forward to it!

**Comment by oguimbal** [comment] 2020-12-10 13:26
`pg-mem@1.4.2` is out. Meaning that all of this should be resolved. Please reopen this (or another ad-hoc issue) if necessary !

**Closed by oguimbal** 2020-12-10 13:26 UTC
Labels: enhancement

**Comment by MirrorBytes** [comment] 2020-12-10 14:40
Awesome! Most of my tests are passing! However, I added a line to your test, and I'm getting a strange error now:

```error
failed to cast text to uuid in string

    🐜 This seems to be an execution error, which means that your request syntax seems okay,
    but the resulting statement cannot be executed → Probably not a pg-mem error.

    *️⃣ Failed SQL statement: SELECT "Form"."id" AS "Form_id", "Form"."createdAt" AS "Form_createdAt", "Form"."updatedAt" AS "Form_updatedAt", "Form"."name" AS "Form_name", "Form"."userId" AS "Form_userId", "Form__user"."id" AS "Form__user_id", "Form__user"."createdAt" AS "Form__user_createdAt", "Form__user"."updatedAt" AS "Form__user_updatedAt", "Form__user"."email" AS "Form__user_email", "Form__user"."name" AS "Form__user_name", "Form__user"."password" AS "Form__user_password" FROM "form" "Form" LEFT JOIN "user" "Form__user" ON "Form__user"."id"="Form"."userId" WHERE "Form"."id" IN ('');
```

Here's the line:

```typescript
const loaded_form = await Form.find({ user });
```

Chaging it to:

```typescript
const loaded_form = await Form.find({ where: { user } });
```

Results in the same error.

**Comment by oguimbal** [comment] 2020-12-10 15:02
Are you sure this usecase could work against a real instance of PG ?

The error is due to the `WHERE "Form"."id" IN ('');`  part of the generated request.   "id" being an `uuid`, the string `''` cannot be cased, and thus the condition is invalid.

**Comment by oguimbal** [comment] 2020-12-10 15:20
I tried adding the line you're refering to to the test.

Works on my machine 😶
![image](https://user-images.githubusercontent.com/8973947/101790739-18af1480-3b03-11eb-9505-830a5ce1e67b.png)
(and `user.id`  is not empty, thus the generated request is not the same)

Is there something that changes between your setup & mine ?

Have you registered extensions to pg-mem like `uuid-ossp`  ?  (When attaching a debugger, I can see that Typeorm is trying to use those... exceptions like `Extension does not exist: uuid-ossp`  are being thown, but it seems that Typeorm catches them fallsback to something else to generate)

**Comment by MirrorBytes** [comment] 2020-12-10 15:33
Here's my setup for pg-mem:

```typescript
import { newDb, DataType } from 'pg-mem';
import { v4 } from 'uuid';

import { User } from '../../entities/user';
import { Form } from '../../entities/form';
import { Submission } from '../../entities/submission';

const db = newDb({
  autoCreateForeignKeyIndices: true,
});

export async function setupTest(schema: string): Promise<void> {
  console.log(schema);
  db.getSchema('pg_catalog').registerFunction({
    name: 'col_description',
    args: [DataType.int, DataType.int],
    returns: DataType.text,
    implementation: () => '',
  });

  db.registerExtension('uuid-ossp', (schema) => {
    schema.registerFunction({
      name: 'uuid_generate_v4',
      returns: DataType.uuid,
      implementation: v4,
    });
  });

  db.registerExtension('citext', (schema) => {
    schema.registerFunction({
      name: 'citext',
      args: [DataType.text],
      returns: DataType.text,
      implementation: (arg: string) => arg.toLocaleLowerCase(),
    });
  });

  const connection = await db.adapters.createTypeormConnection({
    type: 'postgres',
    entities: [User, Form, Submission],
  });

  await connection.synchronize();
}
```

I got it to stop throwing those exceptions with that.

I can confirm my user is populated, and it's id is generated. It just appears that it's not populating in the generated query.
I'm going to play around with my use case for a little bit and see if I can figure out what's happening. This may just be the way I implemented something

**Comment by oguimbal** [comment] 2020-12-10 15:56
That's weird. I now have [the exact same setup as yours](https://github.com/oguimbal/pg-mem/blob/master/src/tests/irl-tests/mirrorbytes.spec.ts)  (no more exceptions), but it works on my side... 

Whats is your exact Typeorm version (as of really installed, not in your package.json) ... `cat node_modules/typeorm/package.json| grep version` ? I've got 0.2.29

`Side note 1`:  The function `col_description` is now embbeded in pg-mem. No need to declare it.

`Side note 2:`  you should wrap your Typeorm connection in a structure that forces your unit test to close the connection once done. For instance, [like this](https://github.com/oguimbal/pg-mem/blob/579e89c89c9eb6a2428fe42fb6e8d622e93d2c9f/src/tests/test-utils.ts#L47)  ... if you dont, and forget to close `connection.close()` at the end of a unit test, it could impact following unit tests (your tests wont be isolated anymore), since Typeorm has static variables that stores the current connection.

**Comment by MirrorBytes** [comment] 2020-12-10 16:04
Based on yarn.lock:

TypeORM: v0.2.29
pg-mem: v1.4.2

Thank you for the tip, I've removed that declaration.

I'm going to try wrapping the tests like you suggest, and running them that way. I'm running quite a number of unit tests with graphql, and the user tests worked perfectly.
The form tests are weird though.. so it pulls the correct forms created by a specified user, but still throws that error.

Let me isolate my tests, then I'll test against the real instance (as a control), then I'll test it against pg-mem.

**Comment by MirrorBytes** [comment] 2020-12-10 17:25
Ok, so in isolation it still throws that error.

**Comment by oguimbal** [comment] 2020-12-10 17:33
```typescript
console.log(user.id);
const loaded_form = await Form.find({ user });
```

What is the console.log showing ?

**Comment by MirrorBytes** [comment] 2020-12-10 17:41
Wow, I messed up the origin of the error. I need more caffeine, sorry for the confusion lol

So, the error is originating from another test where I'm trying to retrieve a form that doesn't exist:

```typescript
const form = await Form.findOne(form, { relations: ['user'] })l
```

It's failing because it's still attempting to pull a form from a user (when that user doesn't exist either).

**Comment by oguimbal** [comment] 2020-12-10 17:44
Haha that happens.

Isnt it supposed to fail, then ?

If not, could you provide some code to reproduce it ?

**Comment by MirrorBytes** [comment] 2020-12-10 17:48
It's supposed to fail, but here's my check:

```typescript
    try {
      const check = await Form.findOne(form, { relations: ['user'] });

      if (!check) return new Result(false, 'Form does not exist!');

      return check;
    } catch (e) {
      return new Result(false, 'Form does not exist!');
    }
```

The error never passed into the catch.

**Comment by oguimbal** [comment] 2020-12-10 17:59
You're sure that its the statement in your try/catch that throws ?? I dont see how this can be 😳
And what is the `form` argument that you're passing to `findOne` ? I guess it has something like { id: '' }  in it ?

**Comment by MirrorBytes** [comment] 2020-12-10 18:05
Positive, and that's correct. The purpose of that try/catch is specifically to catch the string to uuid conversion error that throws when the string does not match a uuid pattern.

Here's the resolver function I'm using with type-graphql:

```typescript
const FormResultUnion = createUnionType({
  name: 'FormResult',
  types: () => [Result, Form],
  resolveType: (val) => {
    if ('ok' in val) return Result;

    if ('name' in val) return Form;

    return undefined;
  },
});

...

  @Query(() => FormResultUnion)
  async form(@Arg('form') form: string): Promise<typeof FormResultUnion> {
    // Avoid GraphQL UUID error.
    try {
      const check = await Form.findOne(form, { relations: ['user'] });

      if (!check) return new Result(false, 'Form does not exist!');

      return check;
    } catch (e) {
      return new Result(false, 'Form does not exist!');
    }
  }
```

The weird part is that the test passes while presenting me with the error message. If I put another test after this one (just a blank), it immediately fails with that error message.

**Comment by MirrorBytes** [comment] 2020-12-10 18:09
Here's a screenshot of it:

![image](https://user-images.githubusercontent.com/22119469/101812096-ed1f3080-3ae8-11eb-98ef-7ab63a28a42f.png)

**Comment by oguimbal** [comment] 2020-12-10 18:32
Ah ! The important bit is  `UnhandledPromiseRejectionWarning`  ...  this is fixed in `pg-mem@1.4.3` ... its just a warning, but agreed, this was not supposed to be here (nor related to any test).

FYI, [this is the fix](https://github.com/oguimbal/pg-mem/commit/fdb4af5da91ceddceb5032ff77ddc987901ef674#diff-5434d7621041e2bbe017e128e361d977a1e34958ea9a3ed45a2ea3e4450b9820)   and [here is how it is tested](https://github.com/oguimbal/pg-mem/blob/b86443f68efc3fa58cb1b1123207e65e1dcb3124/src/tests/irl-tests/mirrorbytes.spec.ts#L137-L164)

**Comment by MirrorBytes** [comment] 2020-12-10 20:19
IT WORKS! 👍 

I can happily say I've converted all my tests to pg-mem without any errors whatsoever!

**Comment by oguimbal** [comment] 2020-12-10 20:23
Glad to hear it 👍  !

**Comment by oguimbal** [comment] 2020-12-10 20:26
Next step to improve testing time: Share the db instance between tests to avoid running `.synchronize()` multiple times (which probably eats up most of your CPU when running a test).

You can do this with restore points, as documented on the readme.

**Comment by MirrorBytes** [comment] 2020-12-10 20:35
I took my tests out of running in band and the time was cut in half. Time for restore points!

Thank you for working on this! Makes testing run quite a bit faster
