### ISSUE TITLE
Use Errors compatible to the Errors from the pg package

### ISSUE THREAD

**Issue by clemens-smartparking** [oguimbal/pg-mem#118] opened 2021-05-19 00:24 UTC
In some of my code I expect my queries to fail and act depending on the output. However, pg-mem Errors are different to pg Errors.

Alternatively an error code or name could be added to QueryError so that it is easier to identify the error type.

**Comment by oguimbal** [comment] 2021-05-19 06:25
Duplicate of #90 

That's already the case. I started adding error codes, but it is a lot of work to add them for every existing exception, and I dont have this kind of time these days :/

**Closed by oguimbal** 2021-05-19 06:25 UTC
