### ISSUE TITLE
pg returns extra two properties symbols in rows

### ISSUE THREAD

**Issue by A7med-Ragheb** [oguimbal/pg-mem#141] opened 2021-07-16 05:55 UTC
I'm using pg-mem with knex for testing and I notice it is returning two extra properties `Symbol()` and `Symbol(_id)` 
What are these properties and how can I remove them, Is there a setting for that?

version: 1.9.11
node: 14.16.0

**Comment by oguimbal** [comment] 2021-07-16 11:00
Hi,

Dupe of #137 :)

**Closed by oguimbal** 2021-07-16 11:00 UTC
